### ISSUE TITLE
Building for IOS

### ISSUE THREAD

**Issue by oreganrob** [jcsilva/docker-kaldi-android#13]
Hi,

I was wondering if you have ever tried building for IOS (obviously not in Docker!).
Should it be similar in principle?

Thanks

**Comment by jcsilva** [comment]
Hi,

I didn't try building it for IOs. And I don't have any idea if it would be
similar. Sorry for not being able to help you.

**Comment by oreganrob** [comment]
ok. Thanks for the swift response! :)
