### ISSUE TITLE
Unable to find image 'docker-kaldi-android:latest' locally

### ISSUE THREAD

**Issue by haidar786** [jcsilva/docker-kaldi-android#2]
sudo docker run -v /home/haidar/kaldi:/opt/kaldi docker-kaldi-android:latest
Unable to find image 'docker-kaldi-android:latest' locally
docker: Error response from daemon: repository docker-kaldi-android not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by haidar786** [comment]
![docker](https://user-images.githubusercontent.com/23493900/27846997-5d3b5474-6154-11e7-9115-ce7566cde921.png)

**Comment by jcsilva** [comment]
Well, it seems you didn't build the image as requested in the README.

But, you may try running 

sudo docker run -v /home/haidar/kaldi:/opt/kaldi jcsilva/docker-kaldi-android:latest

It should work.

**Comment by haidar786** [comment]
Thank you very much now my issue was resolved.
