### ISSUE TITLE
Error of grep OPENFST_VERSION

### ISSUE THREAD

**Issue by kuo77122** [jcsilva/docker-kaldi-android#3]
Hi jcsilva,
Thanks for your awesome project.

I find the Kaldi makefile had been changed to `OPENFST_VERSION ?= 1.6.2`(added char ?) after 16 Aug. This make compile-kaldi.sh run error.

The line 6 in compile-kaldi.sh should be modified to `OPENFST_VERSION *.= *\K(.*)$`

**Comment by jcsilva** [comment]
Hi,

thanks for helping me. Would you like to make a pull request with the correction?
